name: CI

env:
  DB_PORT: 3307

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: longevity_test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3307:3306  # Changed from 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov requests fastapi uvicorn sqlalchemy pymysql python-dotenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install MySQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client

    # .github/workflows/ci.yml  (excerpt)
    - name: Initialize test database
      run: |
        mysql -h 127.0.0.1 -P $DB_PORT -u root -prootpassword \
            -e "CREATE DATABASE IF NOT EXISTS longevity_test;"
        mysql -h 127.0.0.1 -P $DB_PORT -u root -prootpassword \
            longevity_test < sql/schema.sql
        mysql -h 127.0.0.1 -P $DB_PORT -u root -prootpassword \
            longevity_test < sql/01_seed.sql


    # .github/workflows/ci.yml  – Check schema integrity step
    # 1) drop MySQL-only comment lines and SET/ENGINE stuff
    # 2) strip back-ticks and extra spaces
    - name: Check schema integrity
      run: |
        mysqldump \
            --no-data --compact --skip-comments --skip-set-charset \
            --skip-add-drop-table --skip-tz-utc --column-statistics=0 \
            -h 127.0.0.1 -P $DB_PORT -u root -prootpassword \
            longevity_test > tests/schema_from_db.sql

        clean_sql () {
            grep -vE '^(SET|/\*![0-9]{5}|ENGINE=|COLLATE=|ROW_FORMAT=)' "$1" \
              | sed -E 's/`//g' | tr -s " \t"
        }

        diff -w <(clean_sql sql/schema.sql) <(clean_sql tests/schema_from_db.sql)


    - name: Start API server for testing
      run: |
        cd src/api
        nohup python -m uvicorn main:app --host 127.0.0.1 --port 8000 > api.log 2>&1 &
        echo $! > api.pid
        # Give the server a moment to start
        sleep 2
        # Health check to ensure the API is running
        curl --retry 10 --retry-delay 1 --retry-connrefused http://127.0.0.1:8000/ -f
        cd ../..  # Return to root directory

    - name: Run tests
      run: |
        pytest tests/ --cov=src
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_USER: test_user
        MYSQL_PASSWORD: test_password
        MYSQL_DATABASE: longevity_test
        MYSQL_PORT: 3307
        API_URL: http://127.0.0.1:8000

    - name: Stop API server
      run: |
        if [ -f src/api/api.pid ]; then
          kill $(cat src/api/api.pid)
          rm src/api/api.pid
        fi
